# Generated by Django 5.1.5 on 2025-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(blank=True, null=True, verbose_name='ID группы')),
                ('keyword', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subtitle_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок 1')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name='Описание 1')),
                ('subtitle_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок 2')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='Описание 2')),
                ('subtitle_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок 3')),
                ('description_3', models.TextField(blank=True, null=True, verbose_name='Описание 3')),
                ('subtitle_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок 4')),
                ('description_4', models.TextField(blank=True, null=True, verbose_name='Описание 4')),
                ('image_url', models.URLField(verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
