# Generated by Django 5.1.5 on 2025-02-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(blank=True, null=True, verbose_name='ID группы')),
                ('keyword', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image_url', models.URLField(verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={},
        ),
    ]
