# Generated by Django 5.1.5 on 2025-02-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_slidefirst_alter_slide_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='slidefirst',
            name='group_id',
        ),
    ]
