# Generated by Django 5.1.5 on 2025-02-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_slide_group_id_remove_slidefirst_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
    ]
